### ISSUE TITLE
개발 운영 환경 분리

### ISSUE THREAD

**Issue by yunyoung1819** [depromeet/antoon-api#105]
### 👥 작업에 참여한 인원
@yunyoung1819 

### 📑 작업 사항
- 개발 환경(staging)과 운영 환경(prod)을 분리한다.

**Comment by DongGeon0908** [comment]
해당 이슈는 MVP-1 과정을 완료한 이후에 진행하도록 변경되었습니다!

**Comment by DongGeon0908** [comment]
해당 이슈는 추후 진행합니다.
